### PR TITLE
fix: Don't match names with spaces in for .NET packages

### PR DESCRIPTION
**Pull request by jskeet**
This caused a problem with a PR with a title of "Release Firestore libraries version 2.0.0"

### CODE REVIEW

**Comment by jskeet** [comment]
Thanks @busunkim96. Can you merge please? I don't have rights.

**Comment by busunkim96** [comment]
It looks like the intent is for everyone on yoshi has access to this repo, so I'm not sure why it's so locked down. 

https://github.com/googleapis/sloth/blob/4a905f241b44c72ba5c91908a5327b674b8a1419/users.json#L22-L48

**Comment by busunkim96** [comment]
(Will merge after I re-run nox to resolve lint)

**Comment by jskeet** [comment]
Hmm... odd indeed. Will ask Justin.

**Pull request merged**
