### PR TITLE
node: add autorelease: pending label for releasetool start

### PR DESCRIPTION
**Pull request by kinwa91**

### CODE REVIEW

**Comment by theacodes** [comment]
Please do not merge this until we confirm that all node libraries have
release jobs in kokoro.

**Comment by kinwa91** [comment]
Hi Thea, can we merge this first? I am testing it out on https://github.com/googleapis/nodejs-scheduler to see if we have all the release configs step up properly.

**Comment by kinwa91** [comment]
Please let me know when releasetool is released (or if autorelease pulls releasetool from master) :)

**Comment by theacodes** [comment]
autorelease pulls from master

**Pull request merged**
